In [2]:
import torch

In [3]:
x = torch.empty(3, 4) # generates a 'matrix 3/4' with floats
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [4]:
zeros = torch.zeros(2, 3)
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
ones = torch.ones(2, 3)
print(ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [9]:
torch.manual_seed(1)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]])
tensor([[0.3971, 0.7544, 0.5695],
        [0.4388, 0.6387, 0.5247]])
tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]])
tensor([[0.3971, 0.7544, 0.5695],
        [0.4388, 0.6387, 0.5247]])


In [10]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[-2.5986e+33,  2.1216e-42,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6826, 0.3051, 0.4635],
         [0.4550, 0.5725, 0.4980]],

        [[0.9371, 0.6556, 0.3138],
         [0.1980, 0.4162, 0.2843]]])


In [11]:
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    my_device = torch.device('cpu')
print('Device: {}'.format(my_device))

x = torch.rand(2, 2, device=my_device)
print(x)

Device: cpu
tensor([[0.3398, 0.5239],
        [0.7981, 0.7718]])


In [1]:
# load and show an image with Pillow
from PIL import Image
# load the image
image = Image.open('graduation.jpg')
# summarize some details about the image
print(image.format)
print(image.mode)
print(image.size)
# show the image
image.show()

JPEG
RGB
(1280, 800)


In [3]:
# create a thumbnail of an image
from PIL import Image
# load the image
image = Image.open('graduation.jpg')
# report the size of the image
print(image.size)
# create a thumbnail and preserve aspect ratio
image.thumbnail((100,100))
# report the size of the thumbnail
print(image.size)

(1280, 800)
(100, 63)
